version: "3.9"
services:
  microservice1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/:/app/src
      - ./package.json:/app/package.json
    env_file:
      - .env
    ports:
      - "8000:3000"
    environment:
      PORT: 3000
      NODE_ENV: development
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
